services:
  web:
    build: app
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=local.db
      - FLAG=TRX{h3h3_s0rr1_f0r_th3_l0ng_fl4g}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

