version: '3.3'

services:
  dev_mem:
    privileged: true
    build:
        context: .
    ports:
      - '7008:1337'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1000M
  